version: "1"
services:
  - type: web
    name: saar-ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    plan: free
    envVars:
        - key: GEMINI_API_KEY
          sync: false
          value: AIzaSyDKcidO6O_KU7qbnSFIhyQFY6imnHij8Is
        - key: PYTHON_VERSION
          value: 3.10.12





