version: "1"
services:
  - type: web
    name: saar-ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    plan: free
    envVars:
        - key: GEMINI_API_KEY
          sync: true
          value: AIzaSyAcZRM-uzY3yPGqm8oz_eMLGtDZ-woKL1c
        - key: PYTHON_VERSION
          value: 3.10.12



